name: raspcuterie
devices:
  input:
    - name: AM2303
    - name: HX711
  output:
    - name: refrigerator
      type: relay
      gpio: 26
    - name: heater
      type: relay
      gpio: 19
    - name: humidifier
      type: relay
      gpio: 13
    - name: dehumidifier
      type: relay
      gpio: 6
config:
  refrigerator:
    - rule: Stop cooling
      expression: temperature < 12
      action: off
    - rule: Start cooling
      expression: temperature > 15
      action: on
  dehumidifier:
    - rule: Start
      expression: humidity > 77
      action: on
    - rule: Stop
      expression: humidity < 70
      action: off

