name: Raspcuterie
password: worst
devices:
  - type: bme280
    name: bme
    gpio: 4
    prefix: "bme"
  - type: relay
    name: refrigerator
    gpio: 26
  - type: relay
    name: heater
    gpio: 13
    timeout: 1
  - type: relay
    name: humidifier
    gpio: 6
    timeout: 1
  - name: dehumidifier
    type: relay
    gpio: 19
    timeout: 1
  - name: fan
    type: relay
    gpio: 17
    timeout: 1

charts:
  humidity:
    title: "Luchtvochtigheid %"
    series:
      - bme_humidity
      - dehumidifier
      - fan
  temperature:
    title: Temperatuur
    series:
      - bme_temperature
      - refrigerator

control:
  fermenteren_20:
    expires: 2022-04-26 15:00
    rules:
      fan:
        - rule: "Stop"
          expression: "math.ceil(date.minute/15) % 2 == 0"
          action: "off"
        - rule: "Start"
          expression: "math.ceil(date.minute/15) % 2 == 1"
          action: "on"
      refrigerator:
        - rule: "Stop cooling"
          expression: "temperature < 20.0"
          action: "off"
        - rule: "Start cooling"
          expression: "temperature > 20.5"
          action: "on"
  drogen:
    rules:
      fan:
        - rule: "Stop"
          expression: "math.ceil(date.minute/15) % 2 == 0"
          action: "off"
        - rule: "Start"
          expression: "math.ceil(date.minute/15) % 2 == 1"
          action: "on"
      refrigerator:
        - rule: "Stop cooling"
          expression: "temperature < 13.5"
          action: "off"
        - rule: "Start cooling"
          expression: "temperature > 14"
          action: "on"
      dehumidifier:
        - rule: "Start"
          expression: "humidity_avg_3h > 90"
          action: "on"
        - rule: "Stop"
          expression: "humidity_avg_3h < 85"
          action: "off"
