name: raspcuterie
devices:
  input:
    temperature:
      type: AM2302
    weight:
      type: HX711
  output:
    refrigerator:
      type: relay
      gpio: 26
    heater:
      type: relay
      gpio: 19
    humidifier:
      type: relay
      gpio: 13
    dehumidifier:
      type: relay
      gpio: 6
control:
  refrigerator:
    - rule: "Stop cooling"
      expression: "temperature < 12"
      action: "off"
    - rule: "Start cooling"
      expression: "temperature > 15"
      action: "on"
  dehumidifier:
    - rule: "Start"
      expression: "humidity > 77"
      action: "on"
    - rule: "Stop"
      expression: "humidity < 70"
      action: "off"