name: raspcuterie
devices:
  - name: refrigerator
    timeout: 0
    type: "dbrelay"
    gpio: 6
  - name: heater
    timeout: 0
    type: "dbrelay"
    gpio: 19
  - name: humidifier
    timeout: 0
    type: "dbrelay"
    gpio: 26
  - name: dehumidifier
    timeout: 0
    type: "dbrelay"
    gpio: 13
  - name: temperature
    type: "sinus"
  - name: weight
    type: "sinus"
  - name: fuck
    type: "dbrelay"
    timeout: 0
    gpio: 13
    icon: "fa-times"

control:
  default:
    expires: 2020-01-01 10:00
    rules:
      refrigerator:
      - rule: "Stop cooling"
        expression: "temperature < 21"
        action: "off"
      - rule: "Start cooling"
        expression: "temperature > 21"
        action: "on"
      dehumidifier:
      - rule: "Start"
        expression: "humidity > 77"
        action: "on"
      - rule: "Stop"
        expression: "humidity < 70"
        action: "off"
charts:
  humidity:
    title: "Luchtvochtigheid %"
    series:
      - am1_humidity
      - refrigerator
      - fan
  temperature:
    title: Temperatuur
    series:
      - am1_temperature
      - humidifier
  temperature2:
    title: Temperatuur 2
    series:
      - am1_temperature
      - dehumidifier